# Model configuration
model:
  name: "Total3DLayoutEstimationNetwork"  # Good choice - this is the most advanced model
  backbone: "resnet18"  # ResNet18 is fine - lighter and faster than ResNet34
  pretrained: true
  dropout: 0.3  # Reduce from 0.5 to 0.3 to match the paper recommendations

# Training configuration
train:
  batch_size: 32  # Good for your 24GB unified memory
  num_workers: 8  # Good for 12-core CPU
  epochs: 30
  learning_rate: 0.0001  # Should be 0.0001 (1e-4) for Total3D model, not 0.001
  weight_decay: 0.00001  # Should be 0.00001 (1e-5) for Total3D model
  lr_scheduler: "cosine"  # Use cosine scheduler instead of step
  min_lr: 0.000001  # Add this for cosine scheduler
  save_dir: "checkpoints/total3d"  # Better to use subfolder
  clip_grad: true  # Add gradient clipping
  clip_value: 1.0  # Max gradient norm
  early_stopping: true  # Enable early stopping
  patience: 10  # Stop after 10 epochs without improvement

# Dataset configuration
dataset:
  name: "Pix3D"
  root_dir: "/Users/siddhu/PycharmProjects/LayoutEstimation/pix3d"
  img_size: 256
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  data_augmentation: true

# Loss configuration
loss:
  layout_weight: 1.0
  camera_weight: 0.5
  centroid_weight: 1.0
  size_weight: 1.0
  orientation_weight: 0.5
  regularization_weight: 0.01

# Testing/Demo configuration
test:
  checkpoint: "best_model.pth"
  batch_size: 1
  output_dir: "outputs/total3d"
  visualization: true

optimization:
  mixed_precision: true